-- Materiaux calibres — a executer dans l'editeur SQL Supabase.
-- Genere le 2026-08-09, reprend docs/fragments-prompt.md §6 a §11.
-- statut = 'valide' d'emblee (choix explicite, sans test prealable sur un
-- dossier reel — voir docs/fragments-prompt.md §12).

-- Complete le fragment_prompt des 3 lignes deja en base, sans ecraser une
-- valeur deja renseignee.
update materiaux set fragment_prompt = 'toiture en tuiles plates terre cuite, pose à recouvrement régulier, teinte flammée du rouge orangé au brun variant d''une tuile à l''autre, relief marqué en lumière rasante, arêtiers et faîtage de même teinte'
  where categorie = 'toiture' and terme = 'Tuiles plates terre cuite' and fragment_prompt is null;
update materiaux set fragment_prompt = 'façade en enduit taloché finition talochée fine, teinte blanc cassé légèrement chaude, grain de surface discret et régulier, variations tonales douces d''une zone à l''autre selon l''exposition à la lumière'
  where categorie = 'facade' and terme = 'Enduit taloché blanc cassé' and fragment_prompt is null;
update materiaux set fragment_prompt = 'menuiseries en aluminium à profils fins, laquage mat gris anthracite RAL 7016, vitrages clairs aux reflets nets, joints d''assemblage discrets, poignées assorties'
  where categorie = 'menuiseries' and terme = 'Menuiseries aluminium anthracite' and fragment_prompt is null;

-- Nouvelles lignes.
insert into materiaux (terme, categorie, fragment_prompt, statut) values
  ('Tuiles canal terre cuite', 'toiture', 'toiture en tuiles canal terre cuite, pose romaine à courants et couvrants alternés, teinte flammée du rouge orangé au brun variant d''une tuile à l''autre, ondulation régulière du profil, relief marqué en lumière rasante', 'valide'),
  ('Tuiles mécaniques rouge vieilli', 'toiture', 'toiture en tuiles mécaniques à emboîtement, relief longitudinal régulier, teinte rouge sombre aux nuances brunes et orangées variant d''une tuile à l''autre, légère patine naturelle sur les zones exposées aux intempéries', 'valide'),
  ('Ardoise naturelle', 'toiture', 'toiture en ardoise naturelle, pose en écailles à recouvrement régulier, teinte gris anthracite à reflets bleutés selon l''incidence de la lumière, surface clivée légèrement irrégulière, arêtiers et faîtage en zinc de même registre de gris', 'valide'),
  ('Toiture terrasse gravillonnée', 'toiture', 'toiture terrasse gravillonnée, gravillons de calibre régulier en teinte gris clair à beige, répartition homogène sur l''ensemble de la surface, relevés d''étanchéité discrets en périphérie, acrotère en enduit de même teinte que la façade', 'valide'),
  ('Toiture terrasse végétalisée', 'toiture', 'toiture terrasse végétalisée extensive, couvert végétal bas et dense de sedum aux teintes vertes variant du vert franc au vert-gris selon les zones, relief discret de la végétation, acrotère en enduit ou en couvertine métallique en périphérie', 'valide'),
  ('Bac acier gris anthracite', 'toiture', 'toiture en bac acier nervuré, nervures longitudinales régulières, laquage mat gris anthracite RAL 7016, faîtage et rives de même teinte, surface lisse aux reflets doux sous la lumière rasante', 'valide'),
  ('Zinc à joint debout', 'toiture', 'toiture en zinc à joint debout, joints verticaux réguliers marquant le rythme des lés, teinte gris zinc naturel aux reflets changeants selon l''incidence de la lumière, surface légèrement patinée, arêtiers et noues du même métal', 'valide'),
  ('Enduit taloché ocre/sable', 'facade', 'façade en enduit taloché finition talochée fine, teinte ocre sable, grain de surface discret et régulier, variations tonales douces d''une zone à l''autre selon l''exposition à la lumière', 'valide'),
  ('Enduit gratté pierre', 'facade', 'façade en enduit gratté finition grattée fine, teinte pierre naturelle beige clair, texture rugueuse homogène révélant le grain des granulats en lumière rasante, variations tonales discrètes', 'valide'),
  ('Enduit gris clair', 'facade', 'façade en enduit taloché finition talochée fine, teinte gris clair, grain de surface discret et régulier, variations tonales douces d''une zone à l''autre selon l''exposition à la lumière', 'valide'),
  ('Bardage bois naturel', 'facade', 'façade en bardage bois à claire-voie, lames verticales régulières, teinte bois clair naturel au veinage apparent variant légèrement d''une lame à l''autre, léger relief entre les lames en lumière rasante', 'valide'),
  ('Bardage bois grisé', 'facade', 'façade en bardage bois à claire-voie, lames verticales régulières, teinte grisée naturelle homogène au veinage encore lisible, léger relief entre les lames en lumière rasante', 'valide'),
  ('Pierre de pays apparente', 'facade', 'façade en pierre de pays apparente, moellons de tailles irrégulières assemblés à joints beurrés, teinte gris-beige aux variations naturelles marquées d''une pierre à l''autre, relief prononcé en lumière rasante', 'valide'),
  ('Bardage métallique anthracite', 'facade', 'façade en bardage métallique à lames horizontales, laquage mat gris anthracite RAL 7016, joints d''assemblage fins et réguliers, surface lisse aux reflets doux sous la lumière rasante', 'valide'),
  ('Volets battants bois peint', 'volets', 'volets battants en bois peint à lames verticales assemblées, peinture opaque à finition satinée laissant transparaître le fil du bois sous la couche, pentures et ferrures visibles, gonds scellés en tableau', 'valide'),
  ('Volets roulants aluminium blanc', 'volets', 'volets roulants en aluminium laqué blanc, lames horizontales fines et régulières, jeu constant entre les lames, coffre intégré discret en linteau, surface mate et propre', 'valide'),
  ('Volets roulants aluminium anthracite', 'volets', 'volets roulants en aluminium laqué gris anthracite RAL 7016, lames horizontales fines et régulières, coffre intégré discret en linteau, finition mate absorbant la lumière sans reflet spéculaire', 'valide'),
  ('Volets coulissants bois naturel', 'volets', 'volets coulissants en bois naturel à claire-voie, lames verticales régulières laissant filtrer la lumière, teinte bois clair au veinage apparent, rail de guidage fin visible en partie haute', 'valide'),
  ('Volets battants aluminium blanc', 'volets', 'volets battants en aluminium à lames horizontales fixes, laquage opaque blanc satiné, cadre périphérique fin et régulier, pentures et ferrures visibles, gonds scellés en tableau', 'valide'),
  ('Volets battants bois peint bleu', 'volets', 'volets battants en bois peint à lames verticales assemblées, peinture opaque bleu satinée laissant transparaître le fil du bois sous la couche, pentures et ferrures visibles, gonds scellés en tableau', 'valide'),
  ('Volets persiennés bois', 'volets', 'volets persiennés en bois à lames horizontales orientables fixes, peinture opaque satinée laissant transparaître le fil du bois sous la couche, ombres portées régulières des lames sur le mur en lumière rasante', 'valide'),
  ('Brise-soleil orientable aluminium', 'volets', 'brise-soleil en aluminium à lames horizontales orientables, laquage mat gris anthracite, cadre périphérique fin, ombres portées régulières des lames selon leur orientation en lumière rasante', 'valide'),
  ('Menuiseries aluminium blanc', 'menuiseries', 'menuiseries en aluminium à profils fins, laquage mat blanc, vitrages clairs aux reflets nets, joints d''assemblage discrets, poignées assorties', 'valide'),
  ('Menuiseries aluminium gris clair', 'menuiseries', 'menuiseries en aluminium à profils fins, laquage mat gris clair RAL 7035, vitrages clairs aux reflets nets, joints d''assemblage discrets, poignées assorties', 'valide'),
  ('Menuiseries aluminium noir mat', 'menuiseries', 'menuiseries en aluminium à profils fins, laquage mat noir profond, vitrages clairs aux reflets nets, joints d''assemblage discrets, poignées assorties', 'valide'),
  ('Menuiseries bois naturel (chêne clair)', 'menuiseries', 'menuiseries en bois teinte chêne clair, veinage apparent sous vernis satiné, profils aux arêtes nettes, vitrages clairs aux reflets nets, quincaillerie discrète', 'valide'),
  ('Menuiseries bois peint blanc', 'menuiseries', 'menuiseries en bois peint blanc satiné laissant transparaître le fil du bois sous la couche, profils aux arêtes nettes, vitrages clairs aux reflets nets, quincaillerie discrète', 'valide'),
  ('Menuiseries PVC blanc', 'menuiseries', 'menuiseries en PVC blanc à profils fins, surface lisse et mate régulière, vitrages clairs aux reflets nets, joints d''assemblage discrets, poignées assorties', 'valide'),
  ('Menuiseries mixte bois-aluminium', 'menuiseries', 'menuiseries mixtes bois-aluminium, parement intérieur bois teinte chêne clair au veinage apparent, parement extérieur aluminium laqué mat gris anthracite, profils fins, vitrages clairs aux reflets nets', 'valide'),
  ('Pierre reconstituée beige', 'margelles', 'margelles en pierre reconstituée beige, bord droit à arête légèrement adoucie, surface finement grenue, joints fins et réguliers entre les éléments, teinte homogène avec de discrètes variations d''un élément à l''autre', 'valide'),
  ('Travertin', 'margelles', 'margelles en travertin, surface naturellement poreuse aux cavités caractéristiques, veinage horizontal du beige à l''ivoire, arêtes adoucies par le temps, joints fins, la pierre s''assombrissant légèrement là où l''eau la mouille', 'valide'),
  ('Pierre naturelle bouchardée', 'margelles', 'margelles en pierre naturelle à finition bouchardée, surface régulièrement piquetée offrant un relief mat et antidérapant, teinte gris-beige aux variations naturelles marquées d''une pierre à l''autre, arêtes chanfreinées', 'valide'),
  ('Béton lissé gris clair', 'margelles', 'margelles en béton lissé gris clair, surface mate et régulière aux très légères variations de teinte, arête vive légèrement chanfreinée, joints de fractionnement rectilignes', 'valide'),
  ('Pierre naturelle grise', 'margelles', 'margelles en pierre naturelle grise à finition adoucie, surface régulière au grain fin, teinte gris-bleu aux variations naturelles discrètes d''un élément à l''autre, arêtes légèrement chanfreinées, joints fins', 'valide'),
  ('Carrelage grès cérame imitation pierre', 'margelles', 'margelles en carrelage grès cérame imitation pierre, surface antidérapante à relief fin régulier, teinte beige clair homogène aux discrètes variations d''un élément à l''autre, joints fins et réguliers, arête droite légèrement adoucie', 'valide'),
  ('Bois exotique (assorti à la plage)', 'margelles', 'margelles en lames de bois exotique, pose parallèle au bord du bassin, veinage apparent, teinte du miel au brun clair variant légèrement d''une lame à l''autre, arête légèrement adoucie', 'valide'),
  ('Dalles en pierre reconstituée', 'plage', 'plage de piscine en dalles de pierre reconstituée grand format, pose à joints alignés, surface légèrement structurée antidérapante, teinte claire et homogène, joints fins et réguliers', 'valide'),
  ('Lames bois exotique', 'plage', 'plage de piscine en lames de bois exotique, pose parallèle à lames régulières, veinage apparent, teinte du miel au brun clair variant légèrement d''une lame à l''autre, espacement constant laissant voir l''ombre entre les lames', 'valide'),
  ('Lames composite gris', 'plage', 'plage de piscine en lames composite gris, surface rainurée mate et régulière, teinte uniforme aux très légères nuances, espacement constant entre les lames, aspect net et contemporain', 'valide'),
  ('Béton désactivé', 'plage', 'plage de piscine en béton désactivé, granulats apparents de calibre régulier affleurant en surface, teinte du gris clair au beige selon les granulats, joints de fractionnement rectilignes, surface mate et rugueuse au toucher', 'valide'),
  ('Dalles grès cérame grand format', 'plage', 'plage de piscine en dalles de grès cérame grand format, pose à joints alignés fins, surface mate légèrement structurée antidérapante, teinte gris clair homogène aux discrètes variations d''une dalle à l''autre', 'valide'),
  ('Résine drainante', 'plage', 'plage de piscine en résine drainante à granulats apparents, surface continue sans joint, teinte beige aux nuances de granulats variant légèrement, aspect mat et régulier', 'valide'),
  ('Gazon synthétique', 'plage', 'plage de piscine en gazon synthétique, brins individuellement visibles dressés dans des directions légèrement variées, vert sain homogène aux variations de teinte contenues, couverture dense et régulière jusqu''aux bordures', 'valide');
