'use client'
/* eslint-disable @next/next/no-img-element -- URLs signées temporaires, non optimisables. */

import Link from 'next/link'
import { useCallback, useEffect, useState } from 'react'
import { useRouter } from 'next/navigation'
import type { DossierActuel, GenerationDetail, QualityAuditDetail } from '@/lib/rif/depot'
import type { LigneRapport, VerdictControle } from '@/lib/rif/controle-qualite'
import { CATEGORIES_CORRECTION, type CategorieCorrection } from '@/lib/rif/geometrie-3d'
import { lireReponseApi } from '@/lib/rif/reponse-client'
import { Icon, type IconName } from '@/app/ui/Icons'
import { EmptyState, ErrorState, StatusBadge, formatBytes, formatDate } from '@/app/ui/Primitives'
import ConversationRif from './ConversationRif'
import DepotSources from './DepotSources'
import FicheProjet from './FicheProjet'
import BoutonConfirmerFiche from './BoutonConfirmerFiche'

type Tab='vue'|'analyse'|'alignement'|'contraintes'|'generations'|'comparaison'|'qualite'|'details'
type GenerationUI=GenerationDetail&{imageUrl:string|null}
const tabs:Array<{id:Tab;label:string;icon:IconName}>=[{id:'vue',label:'Vue',icon:'image'},{id:'analyse',label:'Analyse 3D',icon:'model'},{id:'alignement',label:'Alignement',icon:'align'},{id:'contraintes',label:'Contraintes',icon:'constraints'},{id:'generations',label:'Générations',icon:'projects'},{id:'comparaison',label:'Comparaison',icon:'compare'},{id:'qualite',label:'Contrôle qualité',icon:'quality'},{id:'details',label:'Détails',icon:'details'}]
const sourceLabels:Record<string,{label:string;authority:string;icon:IconName}>={model_3d:{label:'Modèle 3D',authority:'Géométrie',icon:'model'},revit_view:{label:'Vue projet',authority:'Cadrage',icon:'view'},site_photo:{label:'Photo réelle',authority:'Environnement',icon:'photo'},axonometry:{label:'Axonométrie',authority:'Contrôle spatial',icon:'axonometry'}}
const statusLabels:Record<string,string>={BROUILLON:'Brouillon',SOURCES_RECUES:'Sources reçues',SOURCES_ANALYSEES:'Sources analysées',CONTEXTE_A_CONFIRMER:'Contexte à confirmer',PRET_A_GENERER:'Prêt à générer',GENERATION_EN_COURS:'Génération en cours',CONTROLE_A_EXAMINER:'Contrôle à examiner',VALIDE:'Validé',A_CORRIGER:'À corriger',A_REPRENDRE:'À reprendre',SUSPENDU:'Suspendu',ECHEC:'Échec'}
const criterionLabels:Record<string,string>={cadrage:'Caméra & cadrage',perspective:'Perspective',silhouette:'Silhouette',volumes:'Volumes',toiture:'Toiture',ouvertures:'Ouvertures',implantation:'Implantation',terrain:'Terrain',environnement:'Environnement',materiaux:'Matériaux',lumiere:'Lumière',elements_secondaires:'Éléments secondaires',confidentialite:'Confidentialité',annotations:'Annotations',references_materiau:'Références matériau',isolation:'Éléments inventés'}
const qualityGroups:Record<string,string[]>={Géométrie:['cadrage','perspective','silhouette','volumes','toiture','ouvertures','implantation'],Environnement:['terrain','environnement','elements_secondaires'],Matériaux:['materiaux','references_materiau'],Présentation:['lumiere','confidentialite','annotations','isolation']}
const correctionLabels:Record<CategorieCorrection,string>={MATERIAL:'Matériau',LIGHTING:'Lumière',VEGETATION:'Végétation',LOCAL_ENVIRONMENT:'Environnement local',ARTIFACT_REMOVAL:'Retrait d’artefact',MINOR_PRESENTATION:'Présentation mineure'}

function statusTone(status:string){if(['succeeded','VALIDE','EXTRACTED','ALIGNED'].includes(status))return'success' as const;if(['failed','timed_out','FAILED','UNSUPPORTED','ECHEC'].includes(status))return'danger' as const;if(['running','queued','REVIEW_REQUIRED','CONTEXTE_A_CONFIRMER','A_CORRIGER'].includes(status))return'warning' as const;return'info' as const}

export default function ProjectCockpit({dossier}:{dossier:DossierActuel}){
 const router=useRouter();const[tab,setTab]=useState<Tab>('vue');const[generations,setGenerations]=useState<GenerationUI[]>([]);const[selectedId,setSelectedId]=useState<string|null>(null);const[loading,setLoading]=useState(true);const[error,setError]=useState<string|null>(null);const[audit,setAudit]=useState<QualityAuditDetail|null>(null);const[action,setAction]=useState<string|null>(null);const[validationOpen,setValidationOpen]=useState(false)
 const load=useCallback(async()=>{setLoading(true);setError(null);try{const data=await lireReponseApi<{success:true;generations:GenerationUI[]}>(await fetch(`/api/dossiers/${dossier.id}/generations`,{cache:'no-store'}));setGenerations(data.generations);setSelectedId(current=>current&&data.generations.some(g=>g.id===current)?current:(data.generations.find(g=>g.isCanonical)?.id??data.generations.find(g=>g.status==='succeeded')?.id??data.generations[0]?.id??null))}catch(e){setError(e instanceof Error?e.message:'Historique indisponible.')}finally{setLoading(false)}},[dossier.id])
 useEffect(()=>{const timer=window.setTimeout(()=>{void load()},0);return()=>window.clearTimeout(timer)},[load])
 useEffect(()=>{if(!selectedId)return;fetch(`/api/dossiers/${dossier.id}/generations/${selectedId}`,{cache:'no-store'}).then(r=>lireReponseApi<{success:true;audit:QualityAuditDetail|null}>(r)).then(d=>setAudit(d.audit)).catch(()=>setAudit(null))},[dossier.id,selectedId])
 const selected=generations.find(g=>g.id===selectedId)??null
 const selectedAudit=audit?.generationId===selectedId?audit:null
 const versionNumber=selected?generations.length-generations.indexOf(selected):0
 async function run(path:string,body?:unknown){setAction(path);setError(null);try{await lireReponseApi(await fetch(`/api/dossiers/${dossier.id}/${path}`,{method:'POST',headers:body?{'Content-Type':'application/json'}:undefined,body:body?JSON.stringify(body):undefined}));await load();router.refresh()}catch(e){setError(e instanceof Error?e.message:'Action impossible.')}finally{setAction(null)}}
 async function validate(verdictHuman:VerdictControle,reserves?:string){if(!selected)return;await run(`generations/${selected.id}/audit`,{verdictHuman,reserves});setValidationOpen(false)}
 async function launchQuality(){if(!selected)return;setAction('quality');try{const data=await lireReponseApi<{success:true;report:LigneRapport[];verdictProposed:VerdictControle;auditId:string}>(await fetch(`/api/dossiers/${dossier.id}/generations/${selected.id}/controle-qualite`,{method:'POST'}));setAudit({id:data.auditId,generationId:selected.id,checklistVersion:'LIB-002 V1.6',report:data.report,verdictProposed:data.verdictProposed,verdictHuman:null,reserves:null,validatedBy:null,validatedAt:null,createdAt:new Date().toISOString()})}catch(e){setError(e instanceof Error?e.message:'Contrôle qualité indisponible.')}finally{setAction(null)}}
 const name=dossier.projectState.projectInfo?.name??dossier.dossierRef
 return <div className="cockpit">
  <header className="cockpit-header"><div className="cockpit-title"><Link href="/dossiers" className="cockpit-back" aria-label="Retour aux projets"><Icon name="chevron" style={{transform:'rotate(180deg)'}}/></Link><div><h1>{name}</h1><p>{[dossier.projectState.projectInfo?.type,dossier.projectState.projectInfo?.location,dossier.dossierRef].filter(Boolean).join(' · ')}</p></div></div><div className="cockpit-actions"><StatusBadge tone={statusTone(dossier.etat)}>{statusLabels[dossier.etat]??dossier.etat}</StatusBadge>{dossier.etat==='CONTEXTE_A_CONFIRMER'&&<BoutonConfirmerFiche dossierId={dossier.id}/>}<button className="button button--primary" disabled={dossier.etat!=='PRET_A_GENERER'||action!==null} onClick={()=>run('generer')}><Icon name="sparkle"/>{action==='generer'?'Génération…':'Nouvelle génération'}</button></div></header>
  <nav className="cockpit-tabs" aria-label="Sections du projet">{tabs.map(t=><button className={`cockpit-tab ${tab===t.id?'is-active':''}`} key={t.id} onClick={()=>setTab(t.id)}>{t.label}</button>)}</nav>
  <div className="cockpit-body">
   <aside className="project-panel"><div className="panel-heading"><h2>Sources du projet</h2><button className="icon-button" onClick={()=>setTab('details')} aria-label="Gérer les sources"><Icon name="edit"/></button></div><SourceSummary dossier={dossier}/><p className="authority-note"><strong>Geometry-first.</strong> Le modèle 3D ne fait autorité que lorsqu’un pack réel en a été extrait. En son absence, la vue projet et l’axonométrie restent les références géométriques.</p><div className="panel-section"><div className="panel-heading"><h2>Projet</h2></div><nav className="project-nav">{tabs.map(t=><button key={t.id} className={tab===t.id?'is-active':''} onClick={()=>setTab(t.id)}><Icon name={t.icon}/>{t.label}</button>)}</nav></div></aside>
   <main className="workspace">{error&&<div style={{marginBottom:10}}><ErrorState message={error}/></div>}{tab==='vue'&&<RenderView generations={generations} selected={selected} selectedId={selectedId} setSelectedId={setSelectedId} loading={loading}/>} {tab==='analyse'&&<AnalysisView dossier={dossier}/>} {tab==='alignement'&&<AlignmentView dossier={dossier}/>} {tab==='contraintes'&&<ConstraintsView dossier={dossier}/>} {tab==='generations'&&<GenerationsView generations={generations} selected={selected} setSelectedId={setSelectedId} dossier={dossier} run={run} busy={action!==null}/>} {tab==='comparaison'&&<ComparisonView generations={generations}/>} {tab==='qualite'&&<QualityView selected={selected} audit={selectedAudit} launch={launchQuality} busy={action==='quality'} onValidate={()=>setValidationOpen(true)} onVerdict={validate}/>} {tab==='details'&&<DetailsView dossier={dossier}/>}</main>
   <ConversationRif dossierId={dossier.id} onActivity={load}/>
  </div>
  {validationOpen&&selected&&<ConfirmValidation version={versionNumber} close={()=>setValidationOpen(false)} confirm={()=>validate('validation')}/>}
 </div>
}

function SourceSummary({dossier}:{dossier:DossierActuel}){const ps=dossier.projectState;const entries=['model_3d','revit_view','site_photo','axonometry'];return <>{entries.map(role=>{const meta=sourceLabels[role];const source=role==='model_3d'?ps.modele3D:ps.sources.find(s=>(s.role_confirmed??s.role_detected)===role);const subtitle=source?('originalName'in source&&source.originalName?source.originalName:`${meta.authority} · source réelle`):'Source manquante';return <div className="source-mini" key={role}><span className="source-mini__icon"><Icon name={meta.icon}/></span><span><strong>{meta.label}</strong><small>{subtitle}</small></span><span className="source-mini__state" style={{color:source?'var(--success)':'var(--muted)'}}>{source?'Ajouté':'Absent'}</span></div>})}</>}

function RenderView({generations,selected,selectedId,setSelectedId,loading}:{generations:GenerationUI[];selected:GenerationUI|null;selectedId:string|null;setSelectedId:(id:string)=>void;loading:boolean}){return <section className="render-stage"><div className="viewer">{selected?.imageUrl?<><img src={selected.imageUrl} alt="Rendu architectural sélectionné"/><div className="viewer-toolbar"><button aria-label="Actualiser"><Icon name="refresh"/></button><button aria-label="Comparer"><Icon name="compare"/></button></div><div className="viewer-caption">{selected.isCanonical?'Version de référence · ':''}{selected.type==='correction'?'Correction':'Génération'} · {formatDate(selected.completedAt??selected.startedAt)}</div></>:<div className="viewer-empty"><div className="viewer-empty__drawing"/><h3>{loading?'Chargement du rendu…':'Aucun rendu à afficher'}</h3><p>{selected&&['queued','running'].includes(selected.status)?'Génération en cours. Le backend ne fournit aucun pourcentage fiable.':'Une génération apparaîtra ici dès qu’elle aura produit une image réelle.'}</p></div>}</div><GenerationStrip generations={generations} selectedId={selectedId} setSelectedId={setSelectedId}/></section>}
function GenerationStrip({generations,selectedId,setSelectedId}:{generations:GenerationUI[];selectedId:string|null;setSelectedId:(id:string)=>void}){return <div className="generation-strip" aria-label="Historique des générations">{generations.map((g,i)=><button key={g.id} className={`generation-card ${selectedId===g.id?'is-active':''}`} onClick={()=>setSelectedId(g.id)}><div className="generation-card__thumb">{g.imageUrl?<img src={g.imageUrl} alt=""/>:<Icon name={g.status==='failed'?'warning':'clock'}/>}</div><strong>Version {generations.length-i}{g.isCanonical?' · Réf.':''}</strong><small>{g.status} · {formatDate(g.startedAt)}</small></button>)}{generations.length===0&&<div className="generation-card generation-add"><Icon name="plus"/><strong>Première génération</strong></div>}</div>}

function AnalysisView({dossier}:{dossier:DossierActuel}){const m=dossier.projectState.modele3D;const p=dossier.projectState.geometryPack;const extracted=p?Object.entries(p).filter(([k,v])=>!['schemaVersion','sourceFileId'].includes(k)&&v!==undefined):[];return <section className="workspace-card"><header className="workspace-card__header"><div><p className="eyebrow">Geometry-first</p><h2>Analyse 3D</h2><p>État réel de la source géométrique et de ses artefacts.</p></div>{m&&<StatusBadge tone={statusTone(m.extractionStatus)}>{m.extractionStatus}</StatusBadge>}</header>{!m?<EmptyState icon="model" title="Aucun modèle 3D" description="Ajoutez une maquette numérique pour préparer un futur pack de contraintes. Le format final reste ouvert."/>:<><div className="metric-grid"><Metric label="Fichier" value={m.originalName??m.fileId.slice(0,8)}/><Metric label="Format déclaré" value={m.format.toUpperCase()}/><Metric label="Taille" value={formatBytes(m.sizeBytes)??'Non disponible'}/><Metric label="Artefacts" value={`${m.artifactFileIds.length}`}/></div>{m.extractionStatus==='UPLOADED'&&<div className="notice"><Icon name="warning"/><span><strong>Extracteur non configuré.</strong> Le fichier est déposé, mais aucune route d’extraction n’existe. Aucun verrouillage géométrique renforcé n’est revendiqué.</span></div>}{m.extractionStatus==='FAILED'&&<div className="notice"><Icon name="warning"/><span><strong>Extraction échouée.</strong> {m.erreur??'Le projet reste utilisable selon le mode standard V2.1.'}</span></div>}<div className="data-section"><h3>Geometry Pack</h3>{p?<div className="data-list"><div className="data-row"><span>Version du schéma</span><strong>v{p.schemaVersion}</strong><StatusBadge tone="info">Réel</StatusBadge></div>{extracted.map(([key,value])=><div className="data-row" key={key}><span>{key}</span><strong>{Array.isArray(value)?`${value.length} élément(s)`:typeof value==='string'?value:'Donnée structurée présente'}</strong><StatusBadge tone="success">Extrait</StatusBadge></div>)}</div>:<EmptyState icon="constraints" title="Aucun pack de contraintes" description="Le modèle reste en mode standard V2.1 tant qu’une extraction réelle n’a pas produit de données."/>}</div></>}</section>}
function Metric({label,value}:{label:string;value:string}){return <div className="metric-card"><span>{label}</span><strong>{value}</strong></div>}

function AlignmentView({dossier}:{dossier:DossierActuel}){const a=dossier.projectState.alignment;return <section className="workspace-card"><header className="workspace-card__header"><div><p className="eyebrow">Caméra & site</p><h2>Alignement</h2><p>Correspondance entre le cadrage projet et la photographie cible.</p></div>{a&&<StatusBadge tone={statusTone(a.status)}>{a.status}</StatusBadge>}</header>{!a?<EmptyState icon="align" title="Alignement non démarré" description="Aucun service d’alignement réel n’est branché. L’interface n’affiche ni overlay ni confiance fictive."/>:<><div className="metric-grid"><Metric label="Source caméra" value={a.sourceCameraFileId.slice(0,10)}/><Metric label="Photo cible" value={a.targetPhotoFileId.slice(0,10)}/><Metric label="Confiance" value={a.confidence===undefined?'Non évaluée':`${Math.round(a.confidence*100)} %`}/><Metric label="Statut" value={a.status}/></div>{a.status==='REVIEW_REQUIRED'&&<div className="notice"><Icon name="warning"/><span><strong>Validation humaine nécessaire.</strong> La correspondance semble exploitable mais ne doit pas être acceptée sans revue.</span></div>}{a.observations&&<div className="data-section"><h3>Observations</h3><div className="data-list"><div className="data-row"><span>Analyse</span><strong>{a.observations}</strong></div></div></div>}{a.raisonEchec&&<div className="notice"><Icon name="warning"/><span>{a.raisonEchec}</span></div>}</>}</section>}

function ConstraintsView({dossier}:{dossier:DossierActuel}){const ps=dossier.projectState;const policies=Object.entries(ps.contraintes_libertes??{});const locked=[...ps.locked,...policies.filter(([,p])=>p.geometry_policy==='locked'||p.geometry_policy==='strict').map(([e])=>e)];const modifiable=policies.filter(([,p])=>p.authorized_by&&(p.material_policy==='controlled'||p.appearance_policy==='controlled'||p.lighting_policy==='controlled'));const conditional=policies.filter(([,p])=>!p.authorized_by&&Object.values(p).some(v=>v==='controlled'||v==='creative'));return <section className="workspace-card"><header className="workspace-card__header"><div><p className="eyebrow">Matrice effective</p><h2>Contraintes</h2><p>Uniquement les politiques présentes dans le ProjectState — aucune absence n’est reclassée visuellement.</p></div></header><ConstraintGroup title="Verrouillé" tone="danger" values={[...new Set(locked)]}/><ConstraintGroup title="Modifiable" tone="success" values={modifiable.map(([e])=>e)}/><ConstraintGroup title="Conditionnel" tone="warning" values={conditional.map(([e])=>e)}/>{locked.length+modifiable.length+conditional.length===0&&<EmptyState icon="constraints" title="Aucune contrainte explicite" description="La matrice n’a pas encore été renseignée. L’interface ne déduit pas qu’une donnée absente est verrouillée."/>}{ps.geometryPack?.lockedZones&&<div className="data-section"><h3>Zones issues du pack géométrique</h3><div className="data-list">{ps.geometryPack.lockedZones.map(z=><div className="data-row" key={z}><span>Zone verrouillée</span><strong>{z}</strong><StatusBadge tone="danger">Pack réel</StatusBadge></div>)}</div></div>}</section>}
function ConstraintGroup({title,tone,values}:{title:string;tone:'danger'|'success'|'warning';values:string[]}){if(!values.length)return null;return <div className="constraint-group"><div className="constraint-group__title"><h3>{title}</h3><StatusBadge tone={tone}>{values.length}</StatusBadge></div>{values.map(v=><div className="constraint-row" key={v}><span className="constraint-row__icon"><Icon name={tone==='danger'?'lock':tone==='success'?'edit':'warning'}/></span><span><strong>{v}</strong><small>Politique explicite du ProjectState</small></span><StatusBadge tone={tone}>{title}</StatusBadge></div>)}</div>}

function GenerationsView({generations,selected,setSelectedId,dossier,run,busy}:{generations:GenerationUI[];selected:GenerationUI|null;setSelectedId:(id:string)=>void;dossier:DossierActuel;run:(path:string,body?:unknown)=>Promise<void>;busy:boolean}){const[category,setCategory]=useState<CategorieCorrection>('MATERIAL');const[element,setElement]=useState('');const[result,setResult]=useState('');return <section className="workspace-card"><header className="workspace-card__header"><div><p className="eyebrow">Historique persistant</p><h2>Générations</h2><p>{generations.length} version{generations.length>1?'s':''} rechargée{generations.length>1?'s':''} depuis le backend.</p></div></header>{generations.length===0?<EmptyState icon="image" title="Aucune génération" description="Confirmez d’abord le contexte du projet. Une génération lancée sera persistée et rechargée après actualisation."/>:<div className="data-section"><div className="data-list">{generations.map((g,i)=><button className="data-row" style={{width:'100%',textAlign:'left',background:selected?.id===g.id?'var(--teal-wash)':'white',borderLeft:0,borderRight:0,borderBottom:0}} key={g.id} onClick={()=>setSelectedId(g.id)}><span>Version {generations.length-i}</span><strong>{g.type==='correction'?'Correction':g.type==='restart_from_sources'?'Reprise':'Initiale'} · {formatDate(g.startedAt)}</strong><StatusBadge tone={statusTone(g.status)}>{g.isCanonical?'Référence':g.status}</StatusBadge></button>)}</div></div>}{dossier.etat==='A_CORRIGER'&&selected&&<div className="data-section"><h3>Correction de la version {generations.length-generations.indexOf(selected)}</h3><div className="form-card"><div className="field-grid"><label className="field"><span>Catégorie</span><select value={category} onChange={e=>setCategory(e.target.value as CategorieCorrection)}>{CATEGORIES_CORRECTION.map(c=><option key={c} value={c}>{correctionLabels[c]}</option>)}</select></label><label className="field"><span>Élément à modifier</span><input value={element} onChange={e=>setElement(e.target.value)} placeholder="Ex. bardage bois"/></label></div><label className="field" style={{marginTop:14}}><span>Résultat attendu</span><textarea rows={3} value={result} onChange={e=>setResult(e.target.value)} placeholder="Décrivez précisément la correction locale…"/></label><div className="notice"><Icon name="lock"/><span>Volumes, toiture, ouvertures et implantation restent verrouillés. Un changement architectural exige une mise à jour de la source géométrique ou une reprise depuis les sources.</span></div><div className="quality-actions"><button className="button button--primary" disabled={busy||!element.trim()||!result.trim()} onClick={()=>run('corriger',{categorie:category,elementAModifier:element,resultatAttendu:result})}>Lancer la correction</button></div></div></div>}</section>}

function ComparisonView({generations}:{generations:GenerationUI[]}){const usable=generations.filter(g=>g.status==='succeeded'&&g.imageUrl);const[a,setA]=useState(usable[1]?.id??usable[0]?.id??'');const[b,setB]=useState(usable[0]?.id??'');const[pos,setPos]=useState(50);const ga=usable.find(g=>g.id===a),gb=usable.find(g=>g.id===b);return <section className="workspace-card"><header className="workspace-card__header"><div><p className="eyebrow">Lecture différentielle</p><h2>Comparaison</h2><p>Deux générations réelles, jamais une image dupliquée artificiellement.</p></div></header>{usable.length<2?<EmptyState icon="compare" title="Deux versions sont nécessaires" description="La comparaison sera disponible dès que deux générations réelles auront abouti."/>:<><div className="comparison-controls"><select className="control" value={a} onChange={e=>setA(e.target.value)} aria-label="Version A">{usable.map((g,i)=><option key={g.id} value={g.id}>Version {usable.length-i}</option>)}</select><select className="control" value={b} onChange={e=>setB(e.target.value)} aria-label="Version B">{usable.map((g,i)=><option key={g.id} value={g.id}>Version {usable.length-i}</option>)}</select></div>{ga&&gb&&ga.id!==gb.id?<div className="comparison-viewer"><div className="comparison-layer"><img src={gb.imageUrl!} alt="Version B"/></div><div className="comparison-layer comparison-layer--top" style={{width:`${pos}%`}}><img src={ga.imageUrl!} alt="Version A" style={{width:`${10000/pos}%`,maxWidth:'none'}}/></div><span className="comparison-handle" style={{left:`${pos}%`}}>↔</span><input className="comparison-range" type="range" min="5" max="95" value={pos} onChange={e=>setPos(Number(e.target.value))} aria-label="Curseur de comparaison"/><span className="comparison-label comparison-label--a">Version A</span><span className="comparison-label comparison-label--b">Version B</span></div>:<div className="notice"><Icon name="warning"/><span>Sélectionnez deux versions différentes.</span></div>}</>}</section>}

function QualityView({selected,audit,launch,busy,onValidate,onVerdict}:{selected:GenerationUI|null;audit:QualityAuditDetail|null;launch:()=>void;busy:boolean;onValidate:()=>void;onVerdict:(v:VerdictControle)=>void}){return <section className="workspace-card"><header className="workspace-card__header"><div><p className="eyebrow">LIB-002 · Verdict proposé</p><h2>Contrôle qualité</h2><p>L’audit automatique reste indicatif. La décision humaine est toujours distincte.</p></div>{audit?.verdictHuman?<StatusBadge tone="success">Validé humainement</StatusBadge>:audit?.verdictProposed?<StatusBadge tone="warning">Proposition : {audit.verdictProposed}</StatusBadge>:null}</header>{!selected?<EmptyState icon="quality" title="Aucun rendu sélectionné" description="Sélectionnez une génération terminée pour consulter ou lancer son contrôle."/>:!audit?<EmptyState icon="quality" title="Contrôle qualité non encore exécuté" description="L’audit multimodal appelle le service réel. Il peut être indisponible si la configuration serveur manque." action={<div style={{display:'flex',gap:8}}><button className="button" disabled={busy||selected.status!=='succeeded'} onClick={launch}>{busy?'Analyse…':'Lancer le contrôle qualité'}</button><button className="button button--primary" disabled={selected.status!=='succeeded'} onClick={onValidate}>Valider cette version</button></div>}/>:<>{audit.report.length===0?<div className="notice"><Icon name="details"/><span>Un verdict humain existe, mais aucun rapport détaillé par critère n’a été produit.</span></div>:<div className="quality-groups">{Object.entries(qualityGroups).map(([group,criteria])=><div className="quality-section" key={group}><h3>{group}</h3>{criteria.map(c=>{const line=audit.report.find(l=>l.critere===c);return <div className="quality-line" key={c}><span className="quality-line__text"><strong>{criterionLabels[c]??c}</strong><small>{line?.ecartObserve??line?.sourceControle??'Non évalué'}</small></span><StatusBadge tone={!line?'neutral':line.etat==='conforme'?'success':line.etat==='reserve'?'warning':line.etat==='non_conforme'?'danger':'neutral'}>{line?.etat??'Non évalué'}</StatusBadge></div>})}</div>)}</div>}<div className="quality-actions"><button className="button" onClick={()=>onVerdict('acceptable_avec_reserve')}>Accepter avec réserve</button><button className="button" onClick={()=>onVerdict('correction_ciblee')}>Demander une correction</button><button className="button button--primary" onClick={onValidate}>Valider cette version</button></div></>}</section>}

function DetailsView({dossier}:{dossier:DossierActuel}){const ps=dossier.projectState;return <section className="workspace-card"><header className="workspace-card__header"><div><p className="eyebrow">Dossier & traçabilité</p><h2>Détails du projet</h2><p>Informations, sources, workflow et état Geometry-First réellement disponibles.</p></div></header><div className="data-section"><h3>Informations</h3><div className="data-list"><div className="data-row"><span>Référence</span><strong>{dossier.dossierRef}</strong></div><div className="data-row"><span>Nom</span><strong>{ps.projectInfo?.name??'Non renseigné'}</strong></div><div className="data-row"><span>Type</span><strong>{ps.projectInfo?.type??'Non renseigné'}</strong></div><div className="data-row"><span>Localisation</span><strong>{ps.projectInfo?.location??'Non renseignée'}</strong></div><div className="data-row"><span>Workflow</span><strong>{statusLabels[dossier.etat]??dossier.etat}</strong><StatusBadge tone={statusTone(dossier.etat)}>{dossier.etat}</StatusBadge></div><div className="data-row"><span>Révision</span><strong>{ps.revision}</strong></div><div className="data-row"><span>Mode</span><strong>{ps.mode??'Non déterminé'}</strong></div></div></div><div className="data-section"><h3>Gestion des sources</h3><DepotSources dossierId={dossier.id} sources={ps.sources} directives={ps.localized_directives} modele3D={ps.modele3D}/></div><div className="data-section"><h3>Fiche complète</h3><FicheProjet projectState={ps}/></div><div className="notice notice--info"><Icon name="details"/><span>Les événements sont bien journalisés côté backend, mais aucun contrat de lecture n’est exposé. L’interface n’invente donc pas de timeline.</span></div></section>}

function ConfirmValidation({version,close,confirm}:{version:number;close:()=>void;confirm:()=>void}){useEffect(()=>{const f=(e:KeyboardEvent)=>{if(e.key==='Escape')close()};window.addEventListener('keydown',f);return()=>window.removeEventListener('keydown',f)},[close]);return <div className="modal-backdrop" role="presentation" onMouseDown={e=>{if(e.target===e.currentTarget)close()}}><div className="modal" role="dialog" aria-modal="true" aria-labelledby="validation-title"><span className="modal-icon"><Icon name="quality"/></span><h2 id="validation-title">Définir comme version de référence ?</h2><p>Version {version}. Cette version deviendra la version de référence du projet. Cette décision enregistre un verdict humain et la rend canonique.</p><div className="modal-actions"><button className="button" onClick={close}>Annuler</button><button className="button button--primary" autoFocus onClick={confirm}>Valider</button></div></div></div>}
