-- Ce fichier n'est plus la source de vérité (D-19, 17.09.2026) : le schéma
-- Neon est désormais géré par des migrations versionnées, dans
-- neon/migrations/ (voir 0001_initial_schema.sql pour l'état exact déjà en
-- production, puis les fichiers suivants pour l'historique des
-- changements). Appliquer avec `npm run db:migrate`, voir l'état avec
-- `npm run db:migrate:status`.
--
-- Conservé ici uniquement pour ne pas casser un lien existant — ne plus
-- éditer ce fichier ; toute évolution du schéma passe par une nouvelle
-- migration dans neon/migrations/.
